#!/data/data/com.termux/files/usr/bin/bash

cd $HOME
# Install dependencies
apt upgrade -y
apt install git termux-api fakeroot coreutils gnupg -y

export TERMUX_ADB;

if [ ! "$TERMUX_ADB" ]; then
    TERMUX_ADB="$(command -v termux-adb)"
fi

# Add adb to termux repo
if [ ! -f "$PREFIX/etc/apt/sources.list.d/termux-adb.list" ]; then
  mkdir -p $PREFIX/etc/apt/sources.list.d
  echo -e "deb https://nohajc.github.io termux extras" > $PREFIX/etc/apt/sources.list.d/termux-adb.list
  wget -qP $PREFIX/etc/apt/trusted.gpg.d https://nohajc.github.io/nohajc.gpg
  apt update
  apt install termux-adb -y

# Create executable
cat > $PREFIX/bin/adb <<- EOF
#!/data/data/com.termux/files/usr/bin/bash

export TERMUX_ADB;

if [ ! "$TERMUX_ADB" ]; then
    TERMUX_ADB="$(command -v termux-adb)";
fi

if [ ! -f "$TERMUX_ADB" ]; then
    echo "Could not find $TERMUX_ADB";
    exit 1;
fi

ANDROID_NO_USE_FWMARK_CLIENT=1 fakeroot $TERMUX_ADB $@;
EOF

chmod 700 $PREFIX/bin/adb

git clone https://github.com/xiv3r/termux-reverse-tethering.git
cd termux-reverse-tethering

echo "Done!"
